development:
  adapter: postgresql
  encoding: unicode
  database: db/development_db
  pool: 5
  username: postgres
  password: KV0A8H3o

test:
  adapter: postgresql
  encoding: unicode
  database: db/test_db
  pool: 5
  username: postgres
  password: KV0A8H3o

production:
  adapter: postgresql
  encoding: unicode
  database: db/production_db
  pool: 5
  username: postgres
  password: KV0A8H3o