development:
  adapter: postgresql
  encoding: unicode
  database: development_db
  pool: 5
  username: postgres
  password: KV0A8H3o

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  username: postgres
  password: KV0A8H3o

production:
  adapter: postgresql
  encoding: unicode
  database: production_db
  pool: 5
  username: postgres
  password: KV0A8H3o