require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaperclipImagesController do

  # This should return the minimal set of attributes required to create a valid
  # PaperclipImage. As you add validations to PaperclipImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaperclipImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all paperclip_images as @paperclip_images" do
      paperclip_image = PaperclipImage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paperclip_images).should eq([paperclip_image])
    end
  end

  describe "GET show" do
    it "assigns the requested paperclip_image as @paperclip_image" do
      paperclip_image = PaperclipImage.create! valid_attributes
      get :show, {:id => paperclip_image.to_param}, valid_session
      assigns(:paperclip_image).should eq(paperclip_image)
    end
  end

  describe "GET new" do
    it "assigns a new paperclip_image as @paperclip_image" do
      get :new, {}, valid_session
      assigns(:paperclip_image).should be_a_new(PaperclipImage)
    end
  end

  describe "GET edit" do
    it "assigns the requested paperclip_image as @paperclip_image" do
      paperclip_image = PaperclipImage.create! valid_attributes
      get :edit, {:id => paperclip_image.to_param}, valid_session
      assigns(:paperclip_image).should eq(paperclip_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaperclipImage" do
        expect {
          post :create, {:paperclip_image => valid_attributes}, valid_session
        }.to change(PaperclipImage, :count).by(1)
      end

      it "assigns a newly created paperclip_image as @paperclip_image" do
        post :create, {:paperclip_image => valid_attributes}, valid_session
        assigns(:paperclip_image).should be_a(PaperclipImage)
        assigns(:paperclip_image).should be_persisted
      end

      it "redirects to the created paperclip_image" do
        post :create, {:paperclip_image => valid_attributes}, valid_session
        response.should redirect_to(PaperclipImage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paperclip_image as @paperclip_image" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaperclipImage.any_instance.stub(:save).and_return(false)
        post :create, {:paperclip_image => {  }}, valid_session
        assigns(:paperclip_image).should be_a_new(PaperclipImage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaperclipImage.any_instance.stub(:save).and_return(false)
        post :create, {:paperclip_image => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paperclip_image" do
        paperclip_image = PaperclipImage.create! valid_attributes
        # Assuming there are no other paperclip_images in the database, this
        # specifies that the PaperclipImage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaperclipImage.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => paperclip_image.to_param, :paperclip_image => { "these" => "params" }}, valid_session
      end

      it "assigns the requested paperclip_image as @paperclip_image" do
        paperclip_image = PaperclipImage.create! valid_attributes
        put :update, {:id => paperclip_image.to_param, :paperclip_image => valid_attributes}, valid_session
        assigns(:paperclip_image).should eq(paperclip_image)
      end

      it "redirects to the paperclip_image" do
        paperclip_image = PaperclipImage.create! valid_attributes
        put :update, {:id => paperclip_image.to_param, :paperclip_image => valid_attributes}, valid_session
        response.should redirect_to(paperclip_image)
      end
    end

    describe "with invalid params" do
      it "assigns the paperclip_image as @paperclip_image" do
        paperclip_image = PaperclipImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaperclipImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => paperclip_image.to_param, :paperclip_image => {  }}, valid_session
        assigns(:paperclip_image).should eq(paperclip_image)
      end

      it "re-renders the 'edit' template" do
        paperclip_image = PaperclipImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaperclipImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => paperclip_image.to_param, :paperclip_image => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paperclip_image" do
      paperclip_image = PaperclipImage.create! valid_attributes
      expect {
        delete :destroy, {:id => paperclip_image.to_param}, valid_session
      }.to change(PaperclipImage, :count).by(-1)
    end

    it "redirects to the paperclip_images list" do
      paperclip_image = PaperclipImage.create! valid_attributes
      delete :destroy, {:id => paperclip_image.to_param}, valid_session
      response.should redirect_to(paperclip_images_url)
    end
  end

end
